In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/financial_risk.csv')

In [3]:
df.head(5)

,Age,Gender,Education Level,Marital Status,Income,Credit Score,Loan Amount,Loan Purpose,Employment Status,Years at Current Job,Payment History,Debt-to-Income Ratio,Assets Value,Number of Dependents,City,State,Country,Previous Defaults,Marital Status Change,Risk Rating
0,49,Male,PhD,Divorced,72799.0,688.0,45713.0,Business,Unemployed,19,Poor,0.154313,120228.0,0.0,Port Elizabeth,AS,Cyprus,2.0,2,Low
1,57,Female,Bachelor's,Widowed,NaN,690.0,33835.0,Auto,Employed,6,Fair,0.148920,55849.0,0.0,North Catherine,OH,Turkmenistan,3.0,2,Medium
2,21,Non-binary,Master's,Single,55687.0,600.0,36623.0,Home,Employed,8,Fair,0.362398,180700.0,3.0,South Scott,OK,Luxembourg,3.0,2,Medium
3,59,Male,Bachelor's,Single,26508.0,622.0,26541.0,Personal,Unemployed,2,Excellent,0.454964,157319.0,3.0,Robinhaven,PR,Uganda,4.0,2,Medium
4,25,Non-binary,Bachelor's,Widowed,49427.0,766.0,36528.0,Personal,Unemployed,10,Fair,0.143242,287140.0,NaN,New Heather,IL,Namibia,3.0,1,Low

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16500 entries, 0 to 16499
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    16500 non-null  int64
 1   Gender                 16500 non-null  object
 2   Education Level        16500 non-null  object
 3   Marital Status         16500 non-null  object
 4   Income                 14039 non-null  float64
 5   Credit Score           14029 non-null  float64
 6   Loan Amount            14027 non-null  float64
 7   Loan Purpose           16500 non-null  object
 8   Employment Status      16500 non-null  object
 9   Years at Current Job   16500 non-null  int64
 10  Payment History        16500 non-null  object
 11  Debt-to-Income Ratio   16500 non-null  float64
 12  Assets Value           14035 non-null  float64
 13  Number of Dependents   14017 non-null  float64
 14  City                   16500 non-null  object
 15  State                  16500 non-null  object
 16  Country                16500 non-null  object
 17  Previous Defaults      14027 non-null  float64
 18  Marital Status Change  16500 non-null  int64
 19  Risk Rating            16500 non-null  object
dtypes: float64(7), int64(3), object(10)
memory usage: 2.5+ MB

In [5]:
df.shape

(16500, 20)

In [6]:
df.tail(5)

,Age,Gender,Education Level,Marital Status,Income,Credit Score,Loan Amount,Loan Purpose,Employment Status,Years at Current Job,Payment History,Debt-to-Income Ratio,Assets Value,Number of Dependents,City,State,Country,Previous Defaults,Marital Status Change,Risk Rating
16495,21,Male,Master's,Single,23878.0,723.0,26430.0,Personal,Employed,14,Poor,0.144947,277799.0,0.0,Port Timothy,OH,Tanzania,4.0,0,Low
16496,46,Non-binary,PhD,Married,23553.0,717.0,36363.0,Personal,Self-employed,2,Good,0.462457,161754.0,1.0,Jenniferport,IA,British Virgin Islands,2.0,1,Medium
16497,38,Male,PhD,Widowed,64484.0,714.0,5661.0,Auto,Self-employed,11,Excellent,0.253926,73476.0,2.0,Port Ryantown,HI,Iceland,2.0,2,Medium
16498,68,Male,PhD,Divorced,39693.0,790.0,30117.0,Auto,Unemployed,3,Poor,0.213608,20199.0,3.0,Port Joshuaville,PW,Kazakhstan,1.0,0,Low
16499,23,Female,PhD,Widowed,43039.0,648.0,21655.0,Auto,Unemployed,14,Poor,0.578405,NaN,3.0,South Dennismouth,MS,Uzbekistan,2.0,1,Medium

In [7]:
df.sample(5)

,Age,Gender,Education Level,Marital Status,Income,Credit Score,Loan Amount,Loan Purpose,Employment Status,Years at Current Job,Payment History,Debt-to-Income Ratio,Assets Value,Number of Dependents,City,State,Country,Previous Defaults,Marital Status Change,Risk Rating
13783,47,Female,PhD,Single,NaN,660.0,NaN,Home,Employed,5,Poor,0.444244,231239.0,3.0,New Cynthia,SD,Jamaica,4.0,1,Medium
5423,67,Male,Master's,Married,91082.0,646.0,45024.0,Auto,Self-employed,5,Good,0.594366,62799.0,4.0,Lake James,WA,Mayotte,NaN,1,Medium
14967,29,Male,High School,Single,102013.0,642.0,43842.0,Home,Employed,11,Good,0.568934,NaN,NaN,Andersonfurt,ID,Austria,NaN,0,Medium
1982,36,Male,High School,Widowed,47426.0,795.0,32331.0,Personal,Unemployed,6,Fair,0.563061,111082.0,3.0,New Melvin,FL,Burundi,3.0,1,Low
12157,42,Male,PhD,Divorced,24558.0,739.0,21714.0,Home,Self-employed,11,Good,0.501958,NaN,2.0,North Andreaberg,ND,Cambodia,2.0,2,Medium

In [8]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Marital Status', 'Income',
       'Credit Score', 'Loan Amount', 'Loan Purpose', 'Employment Status',
       'Years at Current Job', 'Payment History', 'Debt-to-Income Ratio',
       'Assets Value', 'Number of Dependents', 'City', 'State', 'Country',
       'Previous Defaults', 'Marital Status Change', 'Risk Rating'],
      dtype='object')

## **Checking missing values**

In [9]:
df.isnull().sum()

Age                         0
Gender                      0
Education Level             0
Marital Status              0
Income                   2461
Credit Score             2471
Loan Amount              2473
Loan Purpose                0
Employment Status           0
Years at Current Job        0
Payment History             0
Debt-to-Income Ratio        0
Assets Value             2465
Number of Dependents     2483
City                        0
State                       0
Country                     0
Previous Defaults        2473
Marital Status Change       0
Risk Rating                 0
dtype: int64

## **check duplicate rows**

In [10]:
df.duplicated().sum()

np.int64(1500)

# **removing duplicate rows**

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

# m**issing values**

In [13]:
df.isnull().sum()

Age                         0
Gender                      0
Education Level             0
Marital Status              0
Income                   2250
Credit Score             2250
Loan Amount              2250
Loan Purpose                0
Employment Status           0
Years at Current Job        0
Payment History             0
Debt-to-Income Ratio        0
Assets Value             2250
Number of Dependents     2250
City                        0
State                       0
Country                     0
Previous Defaults        2250
Marital Status Change       0
Risk Rating                 0
dtype: int64

In [14]:
num_cols = [
    "Income",
    "Credit Score",
    "Loan Amount",
    "Assets Value",
    "Number of Dependents",
    "Previous Defaults"
]

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_3030/2057581265.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [15]:
df.isnull().sum()

Age                      0
Gender                   0
Education Level          0
Marital Status           0
Income                   0
Credit Score             0
Loan Amount              0
Loan Purpose             0
Employment Status        0
Years at Current Job     0
Payment History          0
Debt-to-Income Ratio     0
Assets Value             0
Number of Dependents     0
City                     0
State                    0
Country                  0
Previous Defaults        0
Marital Status Change    0
Risk Rating              0
dtype: int64

In [16]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Marital Status', 'Income',
       'Credit Score', 'Loan Amount', 'Loan Purpose', 'Employment Status',
       'Years at Current Job', 'Payment History', 'Debt-to-Income Ratio',
       'Assets Value', 'Number of Dependents', 'City', 'State', 'Country',
       'Previous Defaults', 'Marital Status Change', 'Risk Rating'],
      dtype='object')

In [17]:
df.columns = df.columns.str.lower().str.replace(" ","_")

In [18]:
df.dtypes

age                        int64
gender                    object
education_level           object
marital_status            object
income                   float64
credit_score             float64
loan_amount              float64
loan_purpose              object
employment_status         object
years_at_current_job       int64
payment_history           object
debt-to-income_ratio     float64
assets_value             float64
number_of_dependents     float64
city                      object
state                     object
country                   object
previous_defaults        float64
marital_status_change      int64
risk_rating               object
dtype: object

In [19]:
df["gender"].unique()

array(['Male', 'Female', 'Non-binary'], dtype=object)

In [20]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [21]:
df.describe(include="all")

,age,gender,education_level,marital_status,income,credit_score,loan_amount,loan_purpose,employment_status,years_at_current_job,payment_history,debt-to-income_ratio,assets_value,number_of_dependents,city,state,country,previous_defaults,marital_status_change,risk_rating
count,15000.000000,15000,15000,15000,15000.000000,15000.000000,15000.000000,15000,15000,15000.000000,15000,15000.000000,15000.000000,15000.000000,15000,15000,15000,15000.00000,15000.000000,15000
unique,NaN,3,4,4,NaN,NaN,NaN,4,3,NaN,4,NaN,NaN,NaN,10614,59,243,NaN,NaN,3
top,NaN,Non-Binary,Bachelor'S,Widowed,NaN,NaN,NaN,Personal,Employed,NaN,Good,NaN,NaN,NaN,East Michael,Co,Congo,NaN,NaN,Low
freq,NaN,5059,3829,3893,NaN,NaN,NaN,3771,5026,NaN,3822,NaN,NaN,NaN,19,282,124,NaN,NaN,9000
mean,43.452667,NaN,NaN,NaN,69909.338733,699.092733,27464.109267,NaN,NaN,9.476267,NaN,0.350438,159684.572600,2.022533,NaN,NaN,NaN,1.99360,0.998467,NaN
std,14.910732,NaN,NaN,NaN,26887.437667,52.762664,11939.231816,NaN,NaN,5.769707,NaN,0.143919,74030.893394,1.301181,NaN,NaN,NaN,1.30632,0.813782,NaN
min,18.000000,NaN,NaN,NaN,20005.000000,600.000000,5000.000000,NaN,NaN,0.000000,NaN,0.100004,20055.000000,0.000000,NaN,NaN,NaN,0.00000,0.000000,NaN
25%,31.000000,NaN,NaN,NaN,48390.000000,659.000000,18235.500000,NaN,NaN,4.000000,NaN,0.227386,103201.000000,1.000000,NaN,NaN,NaN,1.00000,0.000000,NaN
50%,43.000000,NaN,NaN,NaN,69773.000000,699.000000,27544.000000,NaN,NaN,9.000000,NaN,0.350754,159362.000000,2.000000,NaN,NaN,NaN,2.00000,1.000000,NaN
75%,56.000000,NaN,NaN,NaN,91262.500000,739.250000,36518.750000,NaN,NaN,15.000000,NaN,0.476095,215674.250000,3.000000,NaN,NaN,NaN,3.00000,2.000000,NaN
max,69.000000,NaN,NaN,NaN,119997.000000,799.000000,49998.000000,NaN,NaN,19.000000,NaN,0.599970,299999.000000,4.000000,NaN,NaN,NaN,4.00000,2.000000,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    15000 non-null  int64
 1   gender                 15000 non-null  object
 2   education_level        15000 non-null  object
 3   marital_status         15000 non-null  object
 4   income                 15000 non-null  float64
 5   credit_score           15000 non-null  float64
 6   loan_amount            15000 non-null  float64
 7   loan_purpose           15000 non-null  object
 8   employment_status      15000 non-null  object
 9   years_at_current_job   15000 non-null  int64
 10  payment_history        15000 non-null  object
 11  debt-to-income_ratio   15000 non-null  float64
 12  assets_value           15000 non-null  float64
 13  number_of_dependents   15000 non-null  float64
 14  city                   15000 non-null  object
 15  state                  15000 non-null  object
 16  country                15000 non-null  object
 17  previous_defaults      15000 non-null  float64
 18  marital_status_change  15000 non-null  int64
 19  risk_rating            15000 non-null  object
dtypes: float64(7), int64(3), object(10)
memory usage: 2.4+ MB

In [23]:
print(df.select_dtypes(include=['float']).columns)

Index(['income', 'credit_score', 'loan_amount', 'debt-to-income_ratio',
       'assets_value', 'number_of_dependents', 'previous_defaults'],
      dtype='object')

In [24]:
print(df.select_dtypes(include=['object']).columns)

Index(['gender', 'education_level', 'marital_status', 'loan_purpose',
       'employment_status', 'payment_history', 'city', 'state', 'country',
       'risk_rating'],
      dtype='object')

In [25]:
df.columns = df.columns.str.lower().str.replace(" ","_")

int_columns = [
    "age",
    "years_at_current_job",
    "marital_status_change"
]

# Fill NaN values in the specified integer columns before converting to int
for col in int_columns:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        # Fill with median, as was done for other numerical columns
        df[col].fillna(df[col].median(), inplace=True)

df[int_columns] = df[int_columns].astype(int)